<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<!-- Windows11 にデフォで入っている net48 を使っておく。 -->
		<TargetFramework>net48</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<AssemblyName>ScrapRenamer</AssemblyName>
		<RootNamespace>ScrapRenamer</RootNamespace>
		<Version>1.1.0</Version>
		<NoWarn>$(NoWarn);WPF0001</NoWarn>
		<ApplicationIcon>AppIcon/AppIcon.ico</ApplicationIcon>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>

		<SatelliteResourceLanguages>_</SatelliteResourceLanguages>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ModernWpfUI" Version="1.0.0-preview.1" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4022.49" />
		<PackageReference Include="System.Memory" Version="4.6.3" />
		<PackageReference Include="IndexRange" Version="1.0.3" />
		<Resource Include="AppIcon\AppIcon.ico" />
		<Resource Include="AppIcon\AppIcon_x32.png" />
		<Content Include="Views\MainWindow\Editor\**" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" TargetPath="bin\Editor\%(RecursiveDir)%(Filename)%(Extension)" />
		<Content Include="Docs\*" CopyToPublishDirectory="PreserveNewest" TargetPath="%(Filename)%(Extension)" />
		<Content Include="..\LICENSE.txt" CopyToPublishDirectory="PreserveNewest" />
		<Content Include="..\THIRD-PARTY-NOTICES.txt" CopyToPublishDirectory="PreserveNewest" />
	</ItemGroup>

	<!--
		Build時の依存DLLを bin\ 以下に配置する。
	-->
	<Target Name="SetDependencyOutputPath" BeforeTargets="CopyFilesToOutputDirectory">

		<ItemGroup>
			<ReferenceCopyLocalPaths Update="@(ReferenceCopyLocalPaths)">
				<DestinationSubPath>bin\%(Filename)%(Extension)</DestinationSubPath>
			</ReferenceCopyLocalPaths>
		</ItemGroup>

	</Target>

	<!--
		Publish時の依存DLLを bin\ 以下に配置する。
	-->
	<Target Name="SetDependencyPublishPath" AfterTargets="ComputeFilesToPublish">

		<ItemGroup>
			<!-- ルート直下のDLL -->
			<ResolvedFileToPublish Update="@(ResolvedFileToPublish)"
				Condition="'%(ResolvedFileToPublish.Extension)' == '.dll' and
					'%(ResolvedFileToPublish.RelativePath)' == '%(ResolvedFileToPublish.Filename)%(ResolvedFileToPublish.Extension)'"
				RelativePath="bin\%(Filename)%(Extension)" />

			<!-- サブディレクトリにあるDLL -->
			<ResolvedFileToPublish Update="@(ResolvedFileToPublish)"
				Condition="'%(ResolvedFileToPublish.Extension)' == '.dll' and
					'%(ResolvedFileToPublish.RelativePath)' != '%(ResolvedFileToPublish.Filename)%(ResolvedFileToPublish.Extension)' and
					!$([System.String]::Copy('%(ResolvedFileToPublish.RelativePath)').StartsWith('bin\'))"
				RelativePath="bin\%(RelativePath)" />

		</ItemGroup>

	</Target>

	<!--
		Publish時に重複する WebView2Loader.dll を除外する。
	-->
	<Target Name="RemoveDuplicateWebView2LoaderFromPublish"
			AfterTargets="SetDependencyPublishPath">

		<ItemGroup>
			<ResolvedFileToPublish Remove="@(ResolvedFileToPublish)"
				Condition="'%(ResolvedFileToPublish.RelativePath)' == 'bin\runtimes\win-x64\native\WebView2Loader.dll'" />
		</ItemGroup>

	</Target>

	<!--
		XMLドキュメントとPDBをPublish対象から除外する。
	-->
	<Target Name="RemoveDocumentationFilesFromPublish" AfterTargets="ComputeFilesToPublish">
		<ItemGroup>
			<ResolvedFileToPublish
				Remove="@(ResolvedFileToPublish)"
				Condition="'%(ResolvedFileToPublish.Extension)' == '.xml' Or '%(ResolvedFileToPublish.Extension)' == '.pdb'" />
		</ItemGroup>
	</Target>

	<Target Name="CreateZip" AfterTargets="Publish">
		<ZipDirectory SourceDirectory="$(PublishDir)" DestinationFile="$(OutputPath)ScrapRenamer-$(Version).zip" Overwrite="true" />
	</Target>
</Project>
