<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net481</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<AssemblyName>ScrapRenamer</AssemblyName>
		<RootNamespace>ScrapRenamer</RootNamespace>
		<Version>1.0.0</Version>
		<NoWarn>$(NoWarn);WPF0001</NoWarn>
		<ApplicationIcon>AppIcon/AppIcon.ico</ApplicationIcon>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
	</PropertyGroup>

	<ItemGroup>
		<Resource Include="AppIcon\AppIcon.ico" />
		<Resource Include="AppIcon\AppIcon_x32.png" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4022.49" />
		<PackageReference Include="System.Text.Json" Version="10.0.11" />
		<PackageReference Include="System.Memory" Version="4.6.3" />
 		<PackageReference Include="IndexRange" Version="1.0.3" />
 		<Content Include="Editor\**"
			CopyToOutputDirectory="PreserveNewest"
			CopyToPublishDirectory="PreserveNewest"
			TargetPath="bin\%(RecursiveDir)%(Filename)%(Extension)" />
		<Content Include="..\LICENSE.txt"
			CopyToPublishDirectory="PreserveNewest" />
		<Content Include="..\THIRD-PARTY-NOTICES.txt"
			CopyToPublishDirectory="PreserveNewest" />
	</ItemGroup>

	<!--
		Build時の依存DLLを bin\ 以下に配置する。
	-->
	<Target Name="SetDependencyOutputPath"
			BeforeTargets="CopyFilesToOutputDirectory">

		<ItemGroup>
			<ReferenceCopyLocalPaths Update="@(ReferenceCopyLocalPaths)">
				<DestinationSubPath>bin\%(Filename)%(Extension)</DestinationSubPath>
			</ReferenceCopyLocalPaths>
		</ItemGroup>

	</Target>

	<!--
		Publish時の依存DLLを bin\ 以下に配置する。
	-->
	<Target Name="SetDependencyPublishPath"
			AfterTargets="ComputeFilesToPublish">

		<ItemGroup>
			<ResolvedFileToPublish
				Update="@(ResolvedFileToPublish)"
				Condition="'%(ResolvedFileToPublish.Extension)' == '.dll'">

				<RelativePath>bin\%(Filename)%(Extension)</RelativePath>

			</ResolvedFileToPublish>
		</ItemGroup>

	</Target>

	<!--
		XMLドキュメントとPDBをPublish対象から除外する。
	-->
	<Target Name="RemoveDocumentationFilesFromPublish"
			AfterTargets="ComputeFilesToPublish">
		<ItemGroup>
			<ResolvedFileToPublish Remove="@(ResolvedFileToPublish)"
				Condition="'%(ResolvedFileToPublish.Extension)' == '.xml' Or
				           '%(ResolvedFileToPublish.Extension)' == '.pdb'" />
		</ItemGroup>
	</Target>

	<Target Name="CreateZip"
			AfterTargets="Publish">
		<ZipDirectory
			SourceDirectory="$(PublishDir)"
			DestinationFile="$(OutputPath)ScrapRenamer-$(Version).zip"
			Overwrite="true" />
	</Target>
</Project>
